### ISSUE TITLE
Deployment on GH pages unsuccessful

### ISSUE THREAD

**Issue by worktree28** [41aman/coursera-test#1]
![image](https://user-images.githubusercontent.com/60058458/152155521-c2634be1-adac-41d3-a5fb-8930fcbe90d5.png)

**Comment by 41aman** [comment]
![image](https://user-images.githubusercontent.com/55613714/152647271-6dea9c79-675c-4bb8-8e9b-8613e673a840.png)

**Comment by worktree28** [comment]
atleast solve the issue pepega
